sudo: required
services:
  - docker

before_install:
  - docker build -t ccm/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ccm/react-test npm test


after_success:
  - docker build -t anilinr/multi-client ./client
  - docker build -t anilinr/multi-nginx ./nginx
  - docker build -t anilinr/multi-server ./server
  - docker build -t anilinr/multi-worker ./worker  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push anilinr/multi-client
  - docker push anilinr/multi-nginx
  - docker push anilinr/multi-server
  - docker push anilinr/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'Multidocker-env'
  env: 'Multidockerenv-env'
  bucket_name: 'elasticbeanstalk-us-east-1-074938362459'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  
